services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: premily
      POSTGRES_PASSWORD: premily_dev_password
      POSTGRES_DB: premily_db
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
